# Generated by Django 5.2.8 on 2025-11-26 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensores', '0002_alter_tiposensor_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lectura', models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('pH', 'pH'), ('luminosidad', 'Luminosidad')], max_length=50)),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad_medida', models.CharField(default='', max_length=20)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensores.sensor')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='lecturas_le_fecha_c76866_idx'), models.Index(fields=['sensor', '-fecha'], name='lecturas_le_sensor__9201c2_idx')],
            },
        ),
    ]
