# Generated by Django 5.2.8 on 2025-11-26 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensores', '0002_alter_tiposensor_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('condicion', models.CharField(max_length=100)),
                ('valor_umbral', models.FloatField()),
                ('tipo_sensor', models.ForeignKey(blank=True, help_text='(opcional) aplicar regla solo a este tipo de sensor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.tiposensor')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.reglaalerta')),
            ],
        ),
    ]
