# Generated by Django 5.2.8 on 2025-11-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
        ('sensores', '0002_alter_tiposensor_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('CRITICO', 'Crítico'), ('ADVERTENCIA', 'Advertencia'), ('INFO', 'Información')], default='INFO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor_medido', models.FloatField()),
                ('valor_limite', models.FloatField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cultivos.cultivo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='sensores.sensor')),
                ('tipo_alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='alertas.tipoalerta')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
