# Generated by Django 5.2.8 on 2025-11-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposensor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
